spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/querydsl
    driverClassName: org.mariadb.jdbc.Driver
    username: likelion
    password: likelion11
  jpa:
    open-in-view: true
    generate-ddl : true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true




