spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/querydsl
    driverClassName: org.mariadb.jdbc.Driver
    username: likelion
    password: likelion11
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true -> sout 대신 밑에 있는 logging으로 log 대체
        format_sql: true
        use_sql_comments: true # 실행되는 JPQL을 볼 수 있다.

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace -> p6spy 대체




